language: java
notifications:
  hipchat:
    rooms:
      secure: UVwphkz/rCBJMDYzfG7Hv8NF5dZJhqfx1bRF668ybNVhabQFbQsJlVRnf7Aq2BSMjlpB8CMFhEgO3zTovIgFxFbkdSm3TOV40SwRe1c2sbtF4K/WX0cBb8I5JMZTktm06PiST08kktflODDOHixfNgBnIiwEePUM43kLK9fiWug=
deploy:
  provider: releases
  api_key:
    secure: fMvxw11xYVblDZm5nSzLxAYMiX8OUkn6GNN9wy3xR1MwUcVyAjT5JbcNmImShUS6iyCfjNu7eZ1QYdW7ORJLeHRmdVs4zPe6Aciz5jJsAUe3sbDrgaQ67YSZhCS35qnLuH1tMjDQn2rWGAogR9DblTgtLpkgT3PN+jHIwvSLbfo=
  file: build/libs/oracle-soa-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-oracle-soa-plugin
